export const LEAD_TABLE_PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_PAGE_SIZE: 8,
    MAX_PAGE_SIZE: 50,
    MIN_PAGE_SIZE: 1,
}

export const TEAM_MEMBER_TABLE_PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_PAGE_SIZE: 10,
    MAX_PAGE_SIZE: 50,
    MIN_PAGE_SIZE: 1,
}