import type { Metadata } from "next";
import LoadingBar from "./loading-bar";
import { Geist, Geist_Mono } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Provider } from "jotai";
import "./globals.css";
import { SocketProvider } from "@/providers/socket-provider";
import { TooltipProvider } from "@/components/ui/tooltip"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark scrollbar-none">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased custom-scroll`}
      >
        <LoadingBar />
        <TRPCReactProvider>
          <NuqsAdapter>
            <Provider>
              <SocketProvider>
                <TooltipProvider>{children}</TooltipProvider>
              </SocketProvider>
              <Toaster richColors />
            </Provider>
          </NuqsAdapter>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
